// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDveMUI86hDXgWWwqRjkDnDenI3fY_mZj4',
    appId: '1:198779252752:web:5dd10c3720962179be5a95',
    messagingSenderId: '198779252752',
    projectId: 'myproject-c8034',
    authDomain: 'myproject-c8034.firebaseapp.com',
    storageBucket: 'myproject-c8034.firebasestorage.app',
    measurementId: 'G-GN328E4RTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4PYYmVUZNxhM54nQZYgogDPMoD4K0_8Y',
    appId: '1:198779252752:android:e4d8e9fe3ebdc595be5a95',
    messagingSenderId: '198779252752',
    projectId: 'myproject-c8034',
    storageBucket: 'myproject-c8034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_JstbnpPd1ecTYwg1oRiNDGtMvXxMcqQ',
    appId: '1:198779252752:ios:462ac9d389b1f545be5a95',
    messagingSenderId: '198779252752',
    projectId: 'myproject-c8034',
    storageBucket: 'myproject-c8034.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_JstbnpPd1ecTYwg1oRiNDGtMvXxMcqQ',
    appId: '1:198779252752:ios:462ac9d389b1f545be5a95',
    messagingSenderId: '198779252752',
    projectId: 'myproject-c8034',
    storageBucket: 'myproject-c8034.firebasestorage.app',
    iosBundleId: 'com.example.flutterTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDveMUI86hDXgWWwqRjkDnDenI3fY_mZj4',
    appId: '1:198779252752:web:621491f2cbc43289be5a95',
    messagingSenderId: '198779252752',
    projectId: 'myproject-c8034',
    authDomain: 'myproject-c8034.firebaseapp.com',
    storageBucket: 'myproject-c8034.firebasestorage.app',
    measurementId: 'G-2JBEC3ZZ22',
  );
}
